// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsGDb8yrOu4dIuR3ts65OAOdpRjEV2sSg',
    appId: '1:968378210309:web:920cf9bd9b2fd8e983646c',
    messagingSenderId: '968378210309',
    projectId: 'chat-app-33bce',
    authDomain: 'chat-app-33bce.firebaseapp.com',
    storageBucket: 'chat-app-33bce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhkPbGkrD8iV4p2s2RcshlNih7OsjTgY',
    appId: '1:968378210309:android:b3bc478ba67d137f83646c',
    messagingSenderId: '968378210309',
    projectId: 'chat-app-33bce',
    storageBucket: 'chat-app-33bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmKEYRSs5NbA3lPfSJPYJbdeTVzQiChE',
    appId: '1:968378210309:ios:79c24196448664b483646c',
    messagingSenderId: '968378210309',
    projectId: 'chat-app-33bce',
    storageBucket: 'chat-app-33bce.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
